### ISSUE TITLE
Vectors are not always initialized with correct location/rotation

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#165] opened 2017-11-17 22:34 UTC
The initial conditions for this bug are very important. Please start these steps right after loading the sim, and do them in exactly the order listed:

1. Enter the 2nd screen
2. Attach a mass to a spring and let it oscillate
3. Press that mass's "stop" button
4. Enable "Net Force"

<img width="248" alt="screen shot 2017-11-17 at 1 52 00 pm" src="https://user-images.githubusercontent.com/5863899/32968654-44f990f0-cb9f-11e7-940b-da6c7f84cc92.png">

If these are done in a different order (eg. net force is enabled before stopping), then everything will work correctly for the remainder of runtime.

Seen on macOS 10.13.1 Chrome. For phetsims/QA#67.

URL: https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.28/masses-and-springs_en.html
Version: 1.0.0-dev.28 2017-11-10 19:03:33 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4918cd72","branch":"master"},"babel":{"sha":"fcbcac44","branch":"master"},"brand":{"sha":"53cf227b","branch":"master"},"chipper":{"sha":"ca18330e","branch":"master"},"dot":{"sha":"4a1ddd12","branch":"master"},"griddle":{"sha":"6e1983be","branch":"master"},"joist":{"sha":"f34dc747","branch":"master"},"kite":{"sha":"e4c0b773","branch":"master"},"masses-and-springs":{"sha":"9d24969e","branch":"master"},"phet-core":{"sha":"ad21faf3","branch":"master"},"phetcommon":{"sha":"d957aefc","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"8e5b0892","branch":"master"},"scenery-phet":{"sha":"11c7fdb3","branch":"master"},"sherpa":{"sha":"5079b265","branch":"master"},"sun":{"sha":"71295bf0","branch":"master"},"tandem":{"sha":"547eb84d","branch":"master"},"twixt":{"sha":"13905577","branch":"master"}}

**Comment by Denz1994** [comment] 2017-11-21 23:32
I believe the commit  bf504859b1e5ac46b74545ac047fbe5d5e1c83dc might have fixed this.

**Comment by phet-steele** [comment] 2017-11-27 22:04
I think it might have done just that!

**Comment by CWilson4960** [comment] 2018-08-30 18:05
This issue is occurring again in rc.4 
phetsims/QA/issues/180
related to phetsims/masses-and-springs/issues/169 also reopening.
Steps to reproduce:
1. Load sim
2. Go to 2nd screen
3. Check slo mo
4. Hang 100g mass
5. Stop Mass
6. Check net force and acceleration (occurs with just acceleration too)
![mas vectors thingy](https://user-images.githubusercontent.com/31217926/44870191-bc36cc80-ac4c-11e8-93bd-418250acff45.jpeg)
![vectors thingy 3](https://user-images.githubusercontent.com/31217926/44870196-be992680-ac4c-11e8-9c84-17c84e9c5901.jpeg)

Macbook Pro 2012, OS Sierra 10.12.6
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-rc.4/phet/masses-and-springs_all_phet.html
Version: 1.0.0-rc.4 2018-08-24 22:56:24 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Language: en-US
Window: 941x584
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"37d5839c","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"bc1f66fe","branch":"HEAD"},"dot":{"sha":"bd4d7035","branch":"HEAD"},"griddle":{"sha":"7be25724","branch":"HEAD"},"joist":{"sha":"8da47b06","branch":"HEAD"},"kite":{"sha":"3b76b24a","branch":"HEAD"},"masses-and-springs":{"sha":"0cd2d603","branch":"HEAD"},"phet-core":{"sha":"e0cec207","branch":"HEAD"},"phet-io":{"sha":"e5c7148f","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"HEAD"},"phet-io-wrappers":{"sha":"f3701e8d","branch":"HEAD"},"phetcommon":{"sha":"80414edb","branch":"HEAD"},"query-string-machine":{"sha":"1f2322e4","branch":"HEAD"},"scenery":{"sha":"3b05db54","branch":"HEAD"},"scenery-phet":{"sha":"f37bff38","branch":"HEAD"},"sherpa":{"sha":"ded365aa","branch":"HEAD"},"sun":{"sha":"00b9c74c","branch":"HEAD"},"tandem":{"sha":"3e1c8fd3","branch":"HEAD"},"twixt":{"sha":"050e8f19","branch":"HEAD"}}

**Comment by Denz1994** [comment] 2018-09-11 16:34
Can you test on RC 1.0 branch for this fix @KatieWoe?

**Comment by KatieWoe** [comment] 2018-09-11 19:53
@Denz1994 
 I'm unclear as to what you mean.  Do you mean this link: https://phet-dev.colorado.edu/html/masses-and-springs/1.0.0-rc.4/

**Comment by KatieWoe** [comment] 2018-09-11 20:16
This still occurs on master and in the link above. @Denz1994 
![update](https://user-images.githubusercontent.com/41024075/45385215-660f4500-b5cd-11e8-8c8a-c4adce4c7793.PNG)

**Comment by phet-steele** [comment] 2018-09-11 20:26
@KatieWoe he means to not check on master, but to check on the 1.0 branch. The link you provided is the 1.0 branch, but it is not up-to-date. 1.0.0-rc.4 is a snapshot in time and its code will never change. To test on the most up-to-date 1.0, @Denz1994 either needs to make an rc.5 for QA, or you need to have the phet code base checkedout on your local computer, checkout the branch, and serve the sim locally. QA almost never has to do this, so @Denz1994 we would generally do an rc.5 spot check.

Side note: @Denz1994 I don't see why the fix for this shouldn't end up in master since it sounds like they are both broken.

**Comment by Denz1994** [comment] 2018-09-14 21:32
Thanks for the clarification @phet-steele. I applied the changes above to https://phet-dev.colorado.edu/html/masses-and-springs/1.0.0-rc.5/phet/masses-and-springs_en_phet.html @KatieWoe . If the issue is fixed, please reassign to me so I can cherry-pick the relevant changes into master.

**Comment by KatieWoe** [comment] 2018-09-14 21:38
Looks good

**Comment by Denz1994** [comment] 2018-09-17 15:31
Fixes cherry-picked into master #169 #165. Closing.

**Closed as completed by Denz1994** 2018-09-17 15:31 UTC
Labels: type:bug
