### ISSUE TITLE
stringTest=double makes radio buttons touch edge of toolbox

### ISSUE THREAD

**Issue by ghost** [phetsims/masses-and-springs#308] opened 2018-07-25 21:28 UTC
Here's the issue:

![screen shot 2018-07-25 at 3 22 28 pm](https://user-images.githubusercontent.com/31285590/43228524-fedfa1aa-901e-11e8-8910-d49db989f564.png)

Seen on all browsers + macOS.

For phetsims/QA/issues/153.

**Comment by arouinfar** [comment] 2018-07-26 23:49
I think what's happening is that the radio buttons are remaining left-aligned with "Constant Parameter" which collides with the panel border under i18n. Maintaining alignment is desirable, but losing the padding between the strings and panel border isn't.

@Denz1994 I think this panel could be allowed to expand to the left to provide room for long translations, similar to what was done in #293. When the panel expands, the padding between the left side of the strings and panel border should remain the same.

**Comment by Denz1994** [comment] 2018-07-27 20:13
Can you review master @arouinfar? The logic for aligning the panel contents has been slightly refactored.

**Comment by arouinfar** [comment] 2018-07-27 22:18
@Denz1994 the strings are no longer colliding with the border, but it looks like panel isn't expanding, as requested.
![image](https://user-images.githubusercontent.com/8419308/43348674-87441342-91b8-11e8-944c-21cb1c5dd9b1.png)
![image](https://user-images.githubusercontent.com/8419308/43348683-8ec6dd34-91b8-11e8-911a-8b04b9fdbef5.png)

**Comment by Denz1994** [comment] 2018-08-01 18:28
Can you review master now @arouinfar? I need a second eye for the expansion.

**Comment by arouinfar** [comment] 2018-08-01 18:37
@Denz1994 for i18n the new panel width is looking good. However, the panel should only get wider for i18n, but otherwise it can keep the same width as it had before (match spring constant panel width).

**Comment by arouinfar** [comment] 2018-08-01 18:42
Here are some screenshots for comparison.

![image](https://user-images.githubusercontent.com/8419308/43541475-c1fba2d4-9587-11e8-9961-1a40d4187076.png)
![image](https://user-images.githubusercontent.com/8419308/43541440-af54414a-9587-11e8-803f-59ff9f46877b.png)
![image](https://user-images.githubusercontent.com/8419308/43541457-b5260c48-9587-11e8-8110-201d27744872.png)

To summarize
- [x] Spring Length and Spring Constant panels should normally have the same width
- [x] Spring Length (and Spring Constant, if that makes things easier) can expand up to 50 px for i18n
- [x] Constant Parameter title/radio group has too much left padding in master, but rc.2 had the desired layout:
![image](https://user-images.githubusercontent.com/8419308/43541675-367e72a8-9588-11e8-8a5c-ea6c8bf366f1.png)

**Comment by Denz1994** [comment] 2018-08-03 19:17
After further investigation, there are a few things to consider. The contents of the panel is already being scaled because the panel is too small for the default sizes of the contents (hSlider in particular). If we change the maxWidth of the panel it will change the scale of its contents automatically because the contents will have more space to expand to its default size.

There is a potential workaround that includes making the panel larger to fit its content.

Capacitor Lab: Basics has a similar behavior, but the difference is that the content's panel fits within the panel. In fact the panel is relatively large compared to M&S.

Design question: Do we want to enlarge the panels to allow for the panel to expand more pixels before shrinking its contents. There will be a good amount of changes to alignments that would require another round of testing for i18n issues. Thoughts @arouinfar and @ariel-phet?

_Note this suggested change also applies to #293_

**Comment by Denz1994** [comment] 2018-08-03 20:32
In a discussion with @ariel-phet. Check for input from @jonathanolson. If the panels require that they are enlarged, then create a general issue where appropriate. Otherwise, work towards refactoring a workaround that allows for more pixel space.

**Comment by Denz1994** [comment] 2018-08-07 19:06
In a meeting with @ariel-phet and @jonathanolson it was confirmed that the contents of the panel need to fit within the panel, by either making the contents smaller or making the panel a bit larger. @ariel-phet thought it was best to let the panels expand a bit more. @arouinfar can you check if master is good for review?

**Comment by arouinfar** [comment] 2018-08-07 23:04
It's looking pretty good to me! Thanks @Denz1994.

**Comment by arouinfar** [comment] 2018-09-20 19:54
@Denz1994 this is occurring in 1.0. @DianaTavares showed me this:
![image](https://user-images.githubusercontent.com/8419308/45843352-9d23db80-bcdc-11e8-93c1-ec2e5e184c56.png)

**Comment by Denz1994** [comment] 2018-11-06 19:04
The spring options panel on the second scene of the intro screen, described above, has been refactored to use alignBox/alignGroup. This change has a similar structure to the general sim option panels found on the right side of each screen. Assigning to @arouinfar to review.

**Comment by arouinfar** [comment] 2018-11-06 21:39
@Denz1994 master is looking good now
![image](https://user-images.githubusercontent.com/8419308/48095347-c2f43980-e1d1-11e8-9d36-743b318573c1.png)

**Comment by Nancy-Salpepi** [comment] 2023-06-01 21:01
This looks good in 1.1.0-dev.2. 
I see a couple of other string test problems that I will make new issues for.

**Comment by jbphet** [comment] 2023-06-02 17:50
Thanks, closing.

**Closed as completed by jbphet** 2023-06-02 17:50 UTC
Labels: type:i18n, status:ready-for-review
