### ISSUE TITLE
invalid value: -2.16025641025641

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#122] opened 2017-09-13 20:25 UTC
```
Error: Assertion failed: invalid value: -2.16025641025641
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1505257057668/assert/js/assert.js:22:13)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1505257057668/axon/js/Property.js?bust=1505258582768:138:40)
    at updateViewLength (https://bayes.colorado.edu/continuous-testing/snapshot-1505257057668/masses-and-springs/js/common/view/OscillatingSpringNode.js?bust=1505258582768:71:27)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1505257057668/masses-and-springs/js/common/view/OscillatingSpringNode.js?bust=1505258582768:77:7
    at NumberProperty.link (https://bayes.colorado.edu/continuous-testing/snapshot-1505257057668/axon/js/Property.js?bust=1505258582768:245:11)
    at new OscillatingSpringNode (https://bayes.colorado.edu/continuous-testing/snapshot-1505257057668/masses-and-springs/js/common/view/OscillatingSpringNode.js?bust=1505258582768:75:41)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1505257057668/masses-and-springs/js/common/view/SpringView.js?bust=1505258582768:60:24
    at Array.forEach (<anonymous>)
    at IntroScreenView.SpringView [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1505257057668/masses-and-springs/js/common/view/SpringView.js?bust=1505258582768:59:19)
    at IntroScreenView.TwoSpringView [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1505257057668/masses-and-springs/js/common/view/TwoSpringView.js?bust=1505258582768:36:16)
Approximately 9/12/2017, 4:57:37 PM
```

**Comment by Denz1994** [comment] 2017-09-15 17:50
This specific issue was fixed in commit ed08432c00a393d8b4d1f36becd9685a9b7c87f4. The limits on the range values were corrected. I figure more of these will pop up periodically because a lot of these ranges were changed. I will look at Bayes testing report to try to catch them. Thanks for the report.

**Comment by phet-steele** [comment] 2017-09-19 20:11
> I figure more of these will pop up periodically

Yup, here's another one for ya.

```
Error: Assertion failed: invalid value: NaN
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1505848033146/assert/js/assert.js:22:13)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1505848033146/axon/js/Property.js?bust=1505850330078:138:40)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1505848033146/masses-and-springs/js/common/model/Mass.js?bust=1505850330078:144:33)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1505848033146/axon/js/Emitter.js?bust=1505850330078:206:49)
    at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1505848033146/axon/js/Property.js?bust=1505850330078:204:29)
    at DerivedProperty._setAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1505848033146/axon/js/Property.js?bust=1505850330078:193:14)
    at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1505848033146/axon/js/Property.js?bust=1505850330078:140:16)
    at Array.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1505848033146/axon/js/DerivedProperty.js?bust=1505850330078:67:34)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1505848033146/axon/js/Emitter.js?bust=1505850330078:206:49)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1505848033146/axon/js/Property.js?bust=1505850330078:204:29)
```

**Comment by Denz1994** [comment] 2017-09-19 20:12
Thanks for the report. I'll look into this.

**Comment by Denz1994** [comment] 2017-09-26 14:48
I abandoned the use of number property. I believe some of these values were coming up as null and breaking the range values set on them. I will monitor bayes for the rest of the day to confirm that this fixed the problem. I can't reproduce the bug with fuzz testing. Closing for now and will reopen if I see a similar issue.

**Closed as completed by Denz1994** 2017-09-26 14:48 UTC
Labels: type:bug, type:automated-testing
