### ISSUE TITLE
Adjusting browser window size while gravity box is open, causes misplaced menu.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#194] opened 2018-01-22 16:50 UTC
Step to reproduce:
1. Open sim on any screen.
2. Click gravity combo box so the menu is open.
3. While the menu is open, make the browser window smaller.
4. At this point, the menu will be at a weird location away from the combo box.

Found during testing #190.

**Comment by Denz1994** [comment] 2018-01-22 17:23
After doing some investigation, it seems like this is a problem in both projectile motion and CCK Black Body Study. However, this isn't a problem in Models of the Hydrogen Atom and Molecules and Shapes. I don't really know why this is an issue with the combo box but it isn't sim specific to Masses and Springs. Perhaps @jonathanolson, can provide some insight on our next collaboration. session.

**Comment by arouinfar** [comment] 2018-01-22 23:59
@Denz1994 this bug isn't particularly problematic for interviews, as there generally isn't any window-resizing that occurs, so I would prioritize #197 over this bug .

**Comment by phet-steele** [comment] 2018-01-23 17:41
Some discussion of this has occurred in https://github.com/phetsims/sun/issues/237 I believe.

**Comment by ariel-phet** [comment] 2018-06-04 16:29
as @phet-steele mentioned, this is a duplicate of the a sun issue. We will not fix for the current release of Masses and Springs (since a rare use case), but since this issue exists in several sims, we will discuss the main issue at dev meeting.

**Closed as completed by ariel-phet** 2018-06-04 16:29 UTC
Labels: type:bug, type:duplicate
